name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /usr/local/allure
          echo "export PATH=/usr/local/allure/bin:$PATH" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd tests
          pipenv run pytest test_dummyjson_crud.py -v --alluredir=../allure-results --capture=tee-sys

      - name: Generate Allure report
        if: always()
        run: /usr/local/allure/bin/allure generate ../allure-results -o ../allure-report --clean

      - name: Debug generated files
        run: ls -la ../allure-results ../allure-report

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ../allure-results/

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ../allure-report/