name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Debug Python and pipenv versions
        run: |
          python --version
          pipenv --version
          pipenv --python 3.9

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Run tests
        run: |
          cd tests
          pipenv run pytest test_dummyjson_crud.py -v --html=report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: tests/report.html
        if: always()